"""Initial revision

Revision ID: f6aed62e61a7
Revises: ff20251820e8
Create Date: 2024-08-26 22:57:28.628535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6aed62e61a7'
down_revision: Union[str, None] = 'ff20251820e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('molecules',
    sa.Column('identifier', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('smiles', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('identifier'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('smiles')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('molecules')
    # ### end Alembic commands ###
