name: CI

# Triggers the workflow on push and pull request events to the main branch
on:
  push:


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python environment
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Install dependencies (FastAPI, pytest, etc.)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install fastapi uvicorn pytest flake8

      # Run pytest tests
      - name: Run tests
        run: |
          pytest tests/

      # Run flake8 static code analysis
      - name: Run flake8
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
